root: true
env:
  browser: false
  es2020: true
parserOptions:
  ecmaVersion: 2020
  sourceType: module
ignorePatterns:
  - "*.gen.mts"
  - "webpack.config.js"
extends:
  - prettier
  - plugin:@typescript-eslint/recommended
  - plugin:import/typescript
  - plugin:prettier/recommended
rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: none
